"""nayan-changes

Revision ID: 2c2947a38d36
Revises: 94aeb9332ae8
Create Date: 2026-08-22 16:11:06.711401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2947a38d36'
down_revision: Union[str, None] = '94aeb9332ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_shares_id'), 'trip_shares', ['id'], unique=False)
    op.create_index(op.f('ix_trip_shares_share_token'), 'trip_shares', ['share_token'], unique=True)
    op.alter_column('trip_copies', 'original_trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('trip_copies_original_trip_id_fkey', 'trip_copies', type_='foreignkey')
    op.create_foreign_key(None, 'trip_copies', 'trips', ['original_trip_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip_copies', type_='foreignkey')
    op.create_foreign_key('trip_copies_original_trip_id_fkey', 'trip_copies', 'trips', ['original_trip_id'], ['id'])
    op.alter_column('trip_copies', 'original_trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_trip_shares_share_token'), table_name='trip_shares')
    op.drop_index(op.f('ix_trip_shares_id'), table_name='trip_shares')
    op.drop_table('trip_shares')
    # ### end Alembic commands ###
