"""add cities and activities routers

Revision ID: 82c55c76e144
Revises: eb2d8ffeba48
Create Date: 2026-08-22 12:26:05.160375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c55c76e144'
down_revision: Union[str, None] = 'eb2d8ffeba48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
